project:
  title: "Project title"
  output-dir: docs
  type: website
execute: 
  cache: TRUE
website: 
  title: "NWT Muskox Collar Project"
  sidebar:
    style: "docked"
    search: false
    contents: 
      - data_exploration.qmd
      - movement_patterns.qmd