project:
  title: "NWT Muskox"
  output-dir: docs
  type: website
execute: 
  cache: TRUE
website: 
  title: "NWT Muskox Collar Project"
  sidebar:
    style: "docked"
    search: false
    contents: 
      - quarto/01_data_exploration.qmd
      - quarto/02_movement_patterns.qmd
      - quarto/03_home_range.qmd
      - quarto/04_annual_range.qmd
      - quarto/05_seasonal_range.qmd
      - quarto/06_seasonal_range_mod.qmd      
      - quarto/step_selection_functions.qmd