project:
  title: "NWT Muskox"
  output-dir: docs
  type: website
execute: 
  cache: TRUE
website: 
  title: "NWT Muskox Collar Project"
  sidebar:
    style: "docked"
    search: false
    contents: 
      - quarto/data_exploration.qmd
      - quarto/movement_patterns.qmd
      - quarto/home_range.qmd
      - quarto/annual_range.qmd
      - quarto/seasonal_range.qmd
      - quarto/seasonal_range_mod.qmd