project:
  title: "NWT Muskox"
  output-dir: docs
  type: website
execute: 
  cache: TRUE
website: 
  title: "NWT Muskox Collar Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
